stages:
  train:
    cmd: python -m ml.train
    deps:
      - ml/data.py
      - ml/features.py
      - data/loan_2019_20.csv
      - ml/train.py
    outs:
      - models/credit_model_v1.pkl
      - reports
